### ISSUE TITLE
Not receiving anything

### ISSUE THREAD

**Issue by nevahid** [tillnagel/simpletouch#4]
hi there... i've started to program for multitouch surfaces using processing. i searched on net and found some libraries helping me achieve this... one of those libraries is this nice SimpleTouch library.
but it seems i don't receive anything to work with it... i mean when i open one of the examples, it just show the image and by touching it nothing happens.
i found a program called Touch2Tuio and when i ran it, it shows me the ip and port of receiving messages as 172.89.75.66 and 3333 . (not exactly sure about ip number :-) ) bu anyway it's not the default 127.0.0.1 . 
what should i do? anything i'm missing? any configuration? 
thanks

**Comment by tillnagel** [comment]
I assume this to be not an issue with SimpleTouch but with your setup. According to the Touch2Tuio manual it should broadcast messages by default to 127.0.0.1 and port 3333, which is also the default of SimpleTouch. 

Even if you are using another IP or any other settings, you can do so with SimpleTouch by initializing your own TuioClient and passing it to the constructor `SimpleTouch(PApplet p, TuioClient tuioClient)`.

**Comment by tillnagel** [comment]
Please reopen if you think this is due to SimpleTouch.

**Comment by nevahid** [comment]
thanks for answering... i figured out that there is no TUIO server on my computer, meaning i can't get any tuioclient working here, even TUIO demo. do you think it is possible that you catch WM_TOUCH events (windows touch event) instead of tuio touches and work with them? 
thanks again for answering

**Comment by tillnagel** [comment]
Isn't that what Touch2Tuio is for? Are you working with Windows 8 or 10?

**Comment by nevahid** [comment]
i'm working with Windows 10... i had to use processing 2.2.1 in order to use SMT library because i could not work with simpletouch... i think i have to write a class for getting windows touches (as SMT does) for myself... and as you mentioned, SMT uses Touch2tuio to get windows touches, but i can't recieve tuio touches at all... strange :-(
